---
switch_role: leaf

sonic_system:
  hostname: Bleaf1
  interface_naming: standard
  anycast_address:
    ipv4: true
    mac_address: 52:54:00:a5:87:87

sonic_vlans:
  - vlan_id: 1
  - vlan_id: 11
  - vlan_id: 12
  - vlan_id: 21
  - vlan_id: 22
  - vlan_id: 33
  - vlan_id: 901
  - vlan_id: 902
  - vlan_id: 991
   - vlan_id: 993

sonic_vlans_interfaces:
  - name: Portchannel1
    trunk:
      allowed_vlans:
        - vlan: 993
